/**
 * Types for PassKey/Shortcake companion pairing (third pairing method after QR and Pair Code).
 *
 * Protocol reference: https://whatsapp-rust.jlucaso.com/concepts/authentication#companionwebclienttype
 */

/** Request arriving from WA Server via passkey_prologue_request */
export interface PasskeyAssertionRequest {
	challenge: Buffer
	rpId?: string
	allowCredentials: Buffer[]
	userVerification: 'required' | 'preferred' | 'discouraged'
	timeoutMs?: number
	/** Verbatim JSON from the server, forwarded to the authenticator */
	rawOptionsJson: string
}

/** Resolved WebAuthn assertion returned by the consumer's authenticator */
export interface PasskeyAssertion {
	/** JSON in the shape WA expects inside <webauthn_assertion> */
	assertionJson: Buffer
	credentialId: Buffer
}

/** Consumer-implemented interface for resolving WebAuthn assertions */
export interface PasskeyAuthenticator {
	getAssertion(request: PasskeyAssertionRequest): Promise<PasskeyAssertion>
}

/** Ephemeral state during the Shortcake flow — lives in memory, never persisted */
export interface ShortcakeState {
	ephemeralKeyPair: { publicKey: Buffer; privateKey: Buffer }
	/** 32 random bytes generated by the companion; used in commitment hash and verification code */
	companionNonce: Buffer
	/** Serialized CompanionEphemeralIdentity proto (pubKey + deviceType + ref) */
	companionEphemeralIdentityBytes: Buffer
	/** SHA-256(companionEphemeralIdentityBytes || companionNonce) */
	ephemeralCommit: Buffer
	/** Serialized ProloguePayload proto; used as HMAC input for handoffProof */
	prologuePayloadBytes: Buffer
	/** DeviceProps.PlatformType numeric value; baked into the HKDF salt */
	deviceType: number
	/** Pairing ref string; baked into the HKDF salt */
	ref: string
	/** New ADV secret for this pairing session */
	rotatedAdvSecretKey: Buffer
	/** HMAC-SHA256(handoffKey, prologuePayloadBytes) — only present when re-linking */
	handoffProof?: Buffer
	// Set after crsc_continuation:
	/** Server's X25519 ephemeral public key */
	primaryPublicKey?: Buffer
	/** Server-provided nonce used in verification code derivation */
	primaryNonce?: Buffer
	/** X25519 DH output */
	sharedSecret?: Buffer
	/** HKDF-derived AES-256-GCM key for PairingRequest encryption */
	encryptionKey?: Buffer
	/** 8-char Crockford base32 code shown to the user */
	verificationCode?: string
}

/** AES-256-GCM output from encryptPairingRequest */
export interface ShortcakePairingPayload {
	encryptedData: Buffer
	iv: Buffer
	tag: Buffer
}

/** Parameters for constructing the passkey_prologue IQ node */
export interface PasskeyPrologueParams {
	credentialId: Buffer
	assertionJson: Buffer
	/** Serialized ProloguePayload proto (companion_ephemeral_identity + commitment.hash) */
	prologuePayloadBytes: Buffer
	handoffProof?: Buffer
}

/** Data extracted from a crsc_continuation notification */
export interface CrscContinuationData {
	/** Server's X25519 ephemeral public key (DH input) */
	primaryPublicKey: Buffer
	/** Server-provided nonce (XOR input for verification code) */
	primaryNonce: Buffer
	// skip_handoff_ux is NOT sent by the server — computed locally from whether
	// a pairing_handoff_proof was included in the prologue (handoffProof !== undefined)
}

/** Events emitted during the Shortcake/PassKey pairing flow. Entries are merged into BaileysEventMap in Events.ts. */
export type PasskeyEvents = {
	'pairing.passkey-request': { requestOptionsJson: string; deviceId: string }
	'pairing.passkey-confirmation': { code: string; skipHandoffUx: boolean }
	'pairing.passkey-error': { error: string; isContinuable: boolean }
}
